import { Inter } from "next/font/google";
import "./globals.css";
import CommonLayout from "@/components/common-layout";
import { currentUser, fetchUser } from "@/actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await currentUser();
  const ProfileUser = await fetchUser(user?.userId);

  return (
    <html lang="en">
      <body className={inter.className}>
        <CommonLayout user={user} ProfileUser={ProfileUser}>
          {children}
        </CommonLayout>
      </body>
    </html>
  );
}
